export interface Product {
  id: number;
  name: string;
  brand: string;
  price: number;
  oldPrice?: number;
  category: string;
  image: string;
  isOffer?: boolean;
  discount?: number;
  badge?: string;
  description?: string;
  specs?: string[];
  colors?: string[];
}

export interface Category {
  id: number;
  name: string;
  icon: string;
  slug: string;
}

export interface Testimonial {
  id: number;
  name: string;
  avatar: string;
  rating: number;
  comment: string;
  date: string;
}

export interface Benefit {
  id: number;
  title: string;
  description: string;
  icon: string;
}

export const categories: Category[] = [
  { id: 1, name: "Smart TV", icon: "📺", slug: "smart-tv" },
  { id: 2, name: "Celulares", icon: "📱", slug: "celulares" },
  { id: 3, name: "Audio", icon: "🔊", slug: "audio" },
  { id: 4, name: "Refrigeración", icon: "❄️", slug: "refrigeracion" },
  { id: 5, name: "Calefacción", icon: "🔥", slug: "calefaccion" },
  { id: 6, name: "Cocina", icon: "🍳", slug: "cocina" },
  { id: 7, name: "Hogar", icon: "🧹", slug: "hogar" },
  { id: 8, name: "Tecnología", icon: "💻", slug: "tecnologia" },
];

export const products: Product[] = [
  {
    id: 36,
    name: "Cafetera Expreso Yelmo",
    brand: "Yelmo",
    price: 289999,
    oldPrice: 349999,
    category: "Hogar",
    image: "/images/cafeterayelmo.webp",
    isOffer: true,
    discount: 17,
    badge: "OFERTA",
    description: "Cafetera expreso Yelmo con sistema de 15 bares de presión. Prepara un café intenso y aromático con crema perfecta. Diseño compacto y elegante para tu cocina.",
    specs: ["15 bares de presión", "Depósito 1.2L", "Sistema antigoteo", "Calentador rápido", "Bandeja recogegotas extraíble", "Apagado automático"],
  },
  {
    id: 37,
    name: "Cafetera de Cápsulas Yelmo",
    brand: "Yelmo",
    price: 139999,
    oldPrice: 179999,
    category: "Hogar",
    image: "coffee",
    isOffer: true,
    discount: 22,
    badge: "OFERTA",
    description: "Cafetera de cápsulas Yelmo compatible con todas las marcas. Preparamos tu café favorito en segundos con solo presionar un botón.",
    specs: ["Compatible multi-cápsula", "19 bares de presión", "Depósito 0.8L", "Sistema exprés", "Bandeja ajustable", "Limpieza automática"],
  },
  {
    id: 38,
    name: "Cafetera Italiana Yelmo",
    brand: "Yelmo",
    price: 69999,
    oldPrice: 89999,
    category: "Hogar",
    image: "coffee",
    isOffer: true,
    discount: 22,
    badge: "OFERTA",
    description: "Cafetera italiana Yelmo de aluminio pulido. Prepará un café tradicional con el auténtico sabor de siempre. Ideal para 6 tazas.",
    specs: ["Capacidad 6 tazas", "Aluminio pulido", "Mango ergonómico", "Válvula de seguridad", "Apta todo tipo de cocinas", "Fácil limpieza"],
  },
  {
    id: 39,
    name: "Molinillo de Café Yelmo",
    brand: "Yelmo",
    price: 45999,
    oldPrice: 59999,
    category: "Hogar",
    image: "coffee",
    isOffer: true,
    discount: 23,
    badge: "OFERTA",
    description: "Molinillo de café Yelmo con cuchillas de acero inoxidable. Molé tu café recién tostado al instante para obtener el máximo sabor y aroma.",
    specs: ["Potencia 200W", "Cuchillas acero inoxidable", "Capacidad 70g", "Tapa transparente", "Interruptor de seguridad", "Compacto"],
  },
  {
    id: 2,
    name: "iPhone 15 Pro Max 256GB",
    brand: "Apple",
    price: 1899999,
    oldPrice: 2199999,
    category: "Celulares",
    image: "phone",
    isOffer: true,
    discount: 14,
    badge: "OFERTA",
    description: "El iPhone más potente hasta la fecha. Con chip A17 Pro, cámara de 48MP y diseño en titanio. Rendimiento extremo para los que más exigen.",
    specs: ["Pantalla 6.7\" Super Retina XDR", "Chip A17 Pro", "256GB almacenamiento", "Cámara 48MP", "USB-C", "iOS 17"],
  },
  {
    id: 3,
    name: "Parlante Bluetooth Portátil",
    brand: "JBL",
    price: 89999,
    oldPrice: 119999,
    category: "Audio",
    image: "speaker",
    isOffer: true,
    discount: 25,
    badge: "OFERTA",
    description: "Llevá tu música a todos lados con este parlante JBL. Sonido potente, graves profundos y resistencia al agua. Hasta 20 horas de reproducción.",
    specs: ["Potencia 30W", "Bluetooth 5.3", "Resistente al agua IPX7", "20hs batería", "Altavoz stereo", "Microfono incorporado"],
  },
  {
    id: 4,
    name: "Heladera No Frost 400L",
    brand: "LG",
    price: 1299999,
    oldPrice: 1599999,
    category: "Refrigeración",
    image: "fridge",
    isOffer: true,
    discount: 19,
    badge: "OFERTA",
    description: "Heladera LG No Frost con 400 litros de capacidad. Tecnología Smart Inverter que ahorra energía y mantiene tus alimentos frescos por más tiempo.",
    specs: ["400L capacidad total", "No Frost", "Smart Inverter Compressor", "Display digital", "Estantes de vidrio templado", "Cajón verdulero"],
  },
  {
    id: 5,
    name: "Notebook HP Pavilion 15",
    brand: "HP",
    price: 1099999,
    oldPrice: 1349999,
    category: "Tecnología",
    image: "laptop",
    isOffer: true,
    discount: 18,
    badge: "OFERTA",
    description: "Potente notebook HP Pavilion 15 con procesador Intel Core i7 y 16GB de RAM. Ideal para trabajo, estudio y entretenimiento.",
    specs: ["Intel Core i7 13th Gen", "16GB RAM DDR4", "512GB SSD", "Pantalla 15.6\" FHD", "Windows 11", "Teclado retroiluminado"],
  },
  {
    id: 6,
    name: "Cocina 5 Hornallas",
    brand: "Enova",
    price: 699999,
    oldPrice: 849999,
    category: "Cocina",
    image: "stove",
    isOffer: true,
    discount: 18,
    badge: "OFERTA",
    description: "Cocina Enova de 5 hornallas con horno de gran capacidad. Diseño moderno en acero inoxidable y encendido eléctrico seguro.",
    specs: ["5 hornallas", "Horno con visor", "Encendido eléctrico", "Acero inoxidable", "Perilla de seguridad", "Bandeja recolectora"],
  },
  {
    id: 7,
    name: "Aire Acondicionado Split 3000W",
    brand: "Philips",
    price: 899999,
    oldPrice: 1099999,
    category: "Refrigeración",
    image: "ac",
    isOffer: true,
    discount: 18,
    badge: "OFERTA",
    description: "Aire acondicionado Philips Split de 3000W con tecnología inverter. Frío/calor para todo el año. Eficiencia energética A++.",
    specs: ["3000W potencia", "Frío / Calor", "Tecnología Inverter", "Eficiencia A++", "Control remoto", "Filtro antipolvo"],
  },
  {
    id: 8,
    name: "Licuadora Profesional 800W",
    brand: "Liliana",
    price: 45999,
    oldPrice: 58999,
    category: "Hogar",
    image: "blender",
    isOffer: true,
    discount: 22,
    badge: "OFERTA",
    description: "Licuadora Liliana profesional con motor de 800W y 6 velocidades. Vaso de vidrio templado de 1.5L. Ideal para preparar todo tipo de bebidas y mezclas.",
    specs: ["800W de potencia", "Vaso de vidrio 1.5L", "6 velocidades + Pulse", "Cuchillas de acero inoxidable", "Sistema antigoteo", "Base antideslizante"],
  },
  {
    id: 9,
    name: "Freezer Horizontal 200L",
    brand: "Whirlpool",
    price: 749999,
    oldPrice: 899999,
    category: "Refrigeración",
    image: "freezer",
    isOffer: false,
    description: "Freezer horizontal Whirlpool de 200 litros. Ideal para almacenar grandes cantidades de alimentos congelados. Sistema de congelación rápida.",
    specs: ["200L capacidad", "Congelación rápida", "Termostato ajustable", "Cestos organizadores", "Cierre de seguridad", "Eficiencia energética A"],
  },
  {
    id: 10,
    name: "Horno Eléctrico 50L",
    brand: "Atma",
    price: 189999,
    oldPrice: 249999,
    category: "Cocina",
    image: "oven",
    isOffer: true,
    discount: 24,
    badge: "OFERTA",
    description: "Horno eléctrico Atma de 50 litros con función grill y convección. Cocción pareja y rápida. Control de temperatura ajustable.",
    specs: ["50L capacidad", "Función Grill", "Convección", "Control de temperatura", "Temporizador 60min", "Bandeja + rejilla"],
  },
  {
    id: 11,
    name: "Calefactor Eléctrico 2000W",
    brand: "BGH",
    price: 59999,
    oldPrice: 79999,
    category: "Calefacción",
    image: "heater",
    isOffer: true,
    discount: 25,
    badge: "OFERTA",
    description: "Calefactor eléctrico BGH de 2000W con termostato ajustable. Calefacción rápida y eficiente para ambientes de hasta 25m². Seguridad mejorada.",
    specs: ["2000W potencia", "Termostato ajustable", "3 modos de calor", "Apagado automático", "Protección sobrecalentamiento", "Silencioso"],
  },
  {
    id: 12,
    name: "Ventilador de Pie 18",
    brand: "Liliana",
    price: 34999,
    oldPrice: 44999,
    category: "Hogar",
    image: "fan",
    isOffer: true,
    discount: 22,
    badge: "OFERTA",
    description: "Ventilador de pie Liliana con 3 velocidades y oscilación. Ideal para mantener tu hogar fresco en verano. Base estable y diseño moderno.",
    specs: ["18 pulgadas", "3 velocidades", "Oscilación automática", "Base antideslizante", "Rejilla de seguridad", "Bajo consumo"],
  },


  {
    id: 16,
    name: "MacBook Air M4 15\"",
    brand: "Apple",
    price: 2499999,
    oldPrice: 2899999,
    category: "Tecnología",
    image: "laptop",
    isOffer: true,
    discount: 14,
    badge: "OFERTA",
    description: "MacBook Air con chip M4 de Apple. Potencia increíble, batería de hasta 18 horas y diseño ultra delgado. Perfecta para trabajo y creatividad.",
    specs: ["Chip M4 con Neural Engine", "16GB RAM unificada", "512GB SSD", "Pantalla 15.3\" Liquid Retina", "18hs batería", "Touch ID"],
  },
  {
    id: 17,
    name: "iPad Air M2 11\"",
    brand: "Apple",
    price: 1099999,
    oldPrice: 1299999,
    category: "Tecnología",
    image: "laptop",
    isOffer: false,
    description: "iPad Air con chip M2 y pantalla Liquid Retina de 11\". Perfecto para estudios, diseño y entretenimiento con soporte para Apple Pencil.",
    specs: ["Chip M2", "Pantalla 11\" Liquid Retina", "128GB almacenamiento", "Apple Pencil Pro", "Touch ID", "USB-C"],
  },
  {
    id: 18,
    name: "AirPods Pro 2",
    brand: "Apple",
    price: 349999,
    oldPrice: 429999,
    category: "Audio",
    image: "speaker",
    isOffer: true,
    discount: 19,
    badge: "OFERTA",
    description: "AirPods Pro 2 con cancelación de ruido activa y audio espacial personalizado. Chip H2 para un rendimiento de audio superior.",
    specs: ["Cancelación de ruido activa", "Audio espacial personalizado", "Chip H2", "Resistencia IPX4", "6hs batería", "Estuche MagSafe"],
  },
  {
    id: 19,
    name: "Auriculares JBL Tune 770NC",
    brand: "JBL",
    price: 129999,
    oldPrice: 169999,
    category: "Audio",
    image: "speaker",
    isOffer: true,
    discount: 24,
    badge: "OFERTA",
    description: "Auriculares inalámbricos JBL con cancelación de ruido activa y sonido JBL Pure Bass. Hasta 70 horas de reproducción.",
    specs: ["Cancelación de ruido activa", "JBL Pure Bass", "Bluetooth 5.3", "70hs batería", "Plegables", "Micrófono incorporado"],
  },
  {
    id: 20,
    name: "Soundbar JBL Bar 2.1",
    brand: "JBL",
    price: 449999,
    oldPrice: 549999,
    category: "Audio",
    image: "speaker",
    isOffer: true,
    discount: 18,
    badge: "OFERTA",
    description: "Soundbar JBL Bar 2.1 con subwoofer inalámbrico. Potencia de 300W y sonido surround para una experiencia de cine en casa.",
    specs: ["Potencia 300W", "Subwoofer inalámbrico", "Bluetooth 5.1", "HDMI ARC", "Mando a distancia", "Perfil bajo"],
  },
  {
    id: 21,
    name: 'Smart TV LG 65" NanoCell',
    brand: "LG",
    price: 1199999,
    oldPrice: 1449999,
    category: "Smart TV",
    image: "tv",
    isOffer: true,
    discount: 17,
    badge: "OFERTA",
    description: "Smart TV LG NanoCell 65\" con tecnología de puntos cuánticos y procesador a9 Gen6. Colores puros desde cualquier ángulo.",
    specs: ["65 pulgadas", "Resolución 4K NanoCell", "Procesador a9 Gen6", "webOS Smart TV", "Dolby Vision IQ", "Game Optimizer"],
  },
  {
    id: 22,
    name: "Lavarropas LG 7kg Inverter",
    brand: "LG",
    price: 749999,
    oldPrice: 899999,
    category: "Hogar",
    image: "fridge",
    isOffer: true,
    discount: 17,
    badge: "OFERTA",
    description: "Lavarropas LG con motor Inverter de 7kg de capacidad. Eficiencia energética A+++ y funcionamiento silencioso. Programas inteligentes.",
    specs: ["7kg capacidad", "Motor Inverter", "Eficiencia A+++", "6 Motion", "Vapor Steam", "WiFi integrado"],
  },
  {
    id: 23,
    name: "Aire Acondicionado LG Split 3500W",
    brand: "LG",
    price: 999999,
    oldPrice: 1199999,
    category: "Refrigeración",
    image: "ac",
    isOffer: false,
    description: "Aire acondicionado LG Split de 3500W con tecnología Dual Inverter. Máxima eficiencia y enfriamiento rápido para ambientes grandes.",
    specs: ["3500W potencia", "Dual Inverter", "Frío / Calor", "Eficiencia A++", "Filtro antipolvo", "Control WiFi"],
  },
  {
    id: 24,
    name: "Impresora HP Smart Tank 515",
    brand: "HP",
    price: 299999,
    oldPrice: 369999,
    category: "Tecnología",
    image: "laptop",
    isOffer: true,
    discount: 19,
    badge: "OFERTA",
    description: "Impresora HP Smart Tank 515 con sistema de tanque de tinta recargable. Hasta 6000 páginas en color. Ideal para hogar y oficina.",
    specs: ["Sistema tanque recargable", "WiFi + Bluetooth", "Impresión sin bordes", "HP Smart App", "6000 págs color", "Scanner incorporado"],
  },
  {
    id: 25,
    name: 'Monitor HP 27" FHD',
    brand: "HP",
    price: 349999,
    oldPrice: 429999,
    category: "Tecnología",
    image: "tv",
    isOffer: false,
    description: "Monitor HP de 27\" con resolución Full HD y panel IPS. Diseño ultra delgado con bordes finos. Ideal para trabajo y entretenimiento.",
    specs: ["27 pulgadas", "Resolución FHD", "Panel IPS", "75Hz refresco", "Altavoces integrados", "HDMI + VGA"],
  },
  {
    id: 26,
    name: "Anafe Enova 2 Hornallas",
    brand: "Enova",
    price: 149999,
    oldPrice: 189999,
    category: "Cocina",
    image: "stove",
    isOffer: true,
    discount: 21,
    badge: "OFERTA",
    description: "Anafe eléctrico Enova de 2 hornallas con superficie vitrocerámica. Control táctil y seguro para tu cocina. Diseño moderno y fácil de limpiar.",
    specs: ["2 hornallas", "Superficie vitrocerámica", "Control táctil", "Bloqueo de seguridad", "Indicador de calor residual", "Potencia 3000W"],
  },
  {
    id: 27,
    name: "Horno Enova 70L",
    brand: "Enova",
    price: 279999,
    oldPrice: 349999,
    category: "Cocina",
    image: "oven",
    isOffer: true,
    discount: 20,
    badge: "OFERTA",
    description: "Horno eléctrico Enova de 70 litros con función grill y convección. Cocción pareja con control de temperatura digital.",
    specs: ["70L capacidad", "Función Grill", "Convección", "Control digital", "Temporizador", "Luz interior"],
  },
  {
    id: 28,
    name: "Aspiradora Philips PowerPro",
    brand: "Philips",
    price: 199999,
    oldPrice: 259999,
    category: "Hogar",
    image: "fan",
    isOffer: true,
    discount: 23,
    badge: "OFERTA",
    description: "Aspiradora Philips PowerPro con tecnología PowerCyclone 5. Potencia de succión máxima y filtración avanzada para un hogar impecable.",
    specs: ["Potencia 900W", "PowerCyclone 5", "Filtro HEPA", "Bolsa 3L", "Radio 9m", "Accesorios incluidos"],
  },
  {
    id: 29,
    name: "Cafetera Philips LatteGo",
    brand: "Philips",
    price: 699999,
    oldPrice: 849999,
    category: "Hogar",
    image: "blender",
    isOffer: true,
    discount: 18,
    badge: "OFERTA",
    description: "Cafetera superautomática Philips LatteGo con sistema de leche. Café recién molido con un solo toque. 12 niveles de molienda ajustables.",
    specs: ["Sistema LatteGo", "12 niveles molienda", "Depósito 1.8L", "Pantalla táctil", "AquaClean", "Limpieza automática"],
  },
  {
    id: 30,
    name: "Batidora Liliana Planetaria",
    brand: "Liliana",
    price: 89999,
    oldPrice: 119999,
    category: "Hogar",
    image: "blender",
    isOffer: true,
    discount: 25,
    badge: "OFERTA",
    description: "Batidora planetaria Liliana con 5 velocidades y función pulse. Incluye batidor, gancho amasador y varilla. Ideal para preparar masas y mezclas.",
    specs: ["Potencia 600W", "5 velocidades + Pulse", "Bol 4L", "Batidor + gancho + varilla", "Base ventosa", "Cuerpo metálico"],
  },
  {
    id: 31,
    name: "Tostadora Liliana 2 Ranuras",
    brand: "Liliana",
    price: 39999,
    oldPrice: 49999,
    category: "Hogar",
    image: "oven",
    isOffer: true,
    discount: 20,
    badge: "OFERTA",
    description: "Tostadora Liliana con 2 ranuras anchas y 6 niveles de tostado. Función de descongelado y recalentado. Diseño compacto y elegante.",
    specs: ["2 ranuras anchas", "6 niveles de tostado", "Descongelado", "Recalentado", "Bandeja recoge migas", "Cable retráctil"],
  },
  {
    id: 32,
    name: "Pava Eléctrica Atma 1.7L",
    brand: "Atma",
    price: 29999,
    oldPrice: 39999,
    category: "Hogar",
    image: "heater",
    isOffer: true,
    discount: 25,
    badge: "OFERTA",
    description: "Pava eléctrica Atma de 1.7 litros con apagado automático. Base giratoria 360° y filtro antical. Hervido rápido y seguro.",
    specs: ["Capacidad 1.7L", "Apagado automático", "Base 360°", "Filtro antical", "Indicador de nivel", "Potencia 1500W"],
  },
  {
    id: 33,
    name: "Multiprocesadora Atma 1000W",
    brand: "Atma",
    price: 119999,
    oldPrice: 149999,
    category: "Hogar",
    image: "blender",
    isOffer: false,
    description: "Multiprocesadora Atma con motor de 1000W y 2 velocidades. Incluye procesador, batidor y picador. Ideal para preparar tus comidas.",
    specs: ["Potencia 1000W", "2 velocidades", "Vaso 2L", "Batidor + picador", "Cuchillas acero", "Sistema antigoteo"],
  },
  {
    id: 34,
    name: "Microondas BGH 25L",
    brand: "BGH",
    price: 129999,
    oldPrice: 169999,
    category: "Cocina",
    image: "oven",
    isOffer: true,
    discount: 24,
    badge: "OFERTA",
    description: "Microondas BGH de 25 litros con función grill y descongelado rápido. Panel digital con 8 programas automáticos para tu comodidad.",
    specs: ["25L capacidad", "Función Grill", "8 programas automáticos", "Panel digital", "Descongelado rápido", "Puerta espejada"],
  },
  {
    id: 35,
    name: "Aire Acondicionado BGH Split 2500W",
    brand: "BGH",
    price: 799999,
    oldPrice: 949999,
    category: "Refrigeración",
    image: "ac",
    isOffer: true,
    discount: 16,
    badge: "OFERTA",
    description: "Aire acondicionado BGH Split de 2500W con tecnología inverter. Frío/calor con eficiencia energética A++ y funcionamiento silencioso.",
    specs: ["2500W potencia", "Tecnología Inverter", "Frío / Calor", "Eficiencia A++", "Filtro antibacterial", "Control remoto"],
  },
];

export const testimonials: Testimonial[] = [
  {
    id: 1,
    name: "María González",
    avatar: "MG",
    rating: 5,
    comment: "Excelente atención y los precios son los mejores. Me llevé un Smart TV Samsung y el proceso fue súper rápido. Recomiendo totalmente.",
    date: "Hace 2 semanas",
  },
  {
    id: 2,
    name: "Carlos Rodríguez",
    avatar: "CR",
    rating: 5,
    comment: "Compré mi heladera LG acá y no podría estar más contento. La entrega fue en tiempo récord y el producto llegó impecable.",
    date: "Hace 1 mes",
  },
  {
    id: 3,
    name: "Laura Fernández",
    avatar: "LF",
    rating: 5,
    comment: "El equipo de audio que compré superó mis expectativas. Muy buena calidad y el precio imbatible. Sin dudas volveré a comprar.",
    date: "Hace 3 semanas",
  },
  {
    id: 4,
    name: "Martín López",
    avatar: "ML",
    rating: 4,
    comment: "Muy buena variedad de productos. Me asesoraron bien para elegir mi aire acondicionado. Lo recomiendo.",
    date: "Hace 1 semana",
  },
  {
    id: 5,
    name: "Sofía Martínez",
    avatar: "SM",
    rating: 5,
    comment: "Compré varios electrodomésticos para mi casa nueva. Todo perfecto, los precios son muy competitivos y la atención de primera.",
    date: "Hace 2 meses",
  },
];

export const benefits: Benefit[] = [
  {
    id: 1,
    title: "Atención Personalizada",
    description: "Te asesoramos para que encuentres lo que necesitás",
    icon: "headphones",
  },
  {
    id: 2,
    title: "Envíos a todo el país",
    description: "Recibí tu producto donde quieras, rápido y seguro",
    icon: "truck",
  },
  {
    id: 3,
    title: "Productos Originales",
    description: "Trabajamos solo con marcas oficiales y garantía real",
    icon: "shield",
  },
  {
    id: 4,
    title: "Garantía Oficial",
    description: "Todos nuestros productos cuentan con garantía de fábrica",
    icon: "award",
  },
  {
    id: 5,
    title: "Mejores Medios de Pago",
    description: "Efectivo, transferencia, tarjetas y cuotas sin interés",
    icon: "credit-card",
  },
];

export const brands: string[] = [
  "Yelmo",
  "LG",
  "Enova",
  "Gadnic",
  "Philips",
  "Atma",
  "Liliana",
  "BGH",
  "Noblex",
  "Whirlpool",
  "HP",
  "Apple",
  "JBL",
  "Sony",
  "Panasonic",
];

export const siteConfig = {
  name: "ELECTRO BEST",
  description: "Todo para tu hogar y tu tecnología, en un solo lugar.",
  slogan: "Las mejores marcas, precios competitivos y atención personalizada.",
  phone: "381 4889847",
  whatsapp: "5493814889847",
  email: "info@electrobest.com.ar",
  address: "Av. Roca 1604",
  city: "San Miguel de Tucumán",
  province: "Tucumán",
  hours: {
    weekdays: "8:30 – 13:00 | 16:00 – 20:00",
    saturday: "8:30 – 13:00",
  },
  social: {
    instagram: "https://instagram.com/electrobest",
    facebook: "https://facebook.com/electrobest",
    whatsapp: "https://wa.me/5493814889847",
  },
};
